import sys
import os
import json
from langchain_core.messages import HumanMessage, AIMessage

# Add parent directory to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from utils.db import get_snowpark_session, get_snowflake_connection
from utils.meal_router_agent import MealRouterAgent

def reproduce_context_failure(session, conn):
    print("\n" + "="*50)
    print("REPRODUCING CONTEXT FAILURE")
    print("="*50)
    
    try:
        agent = MealRouterAgent(session, conn)
        user_id = "test_user_context"
        
        # Simulate conversation history
        # 1. User asks about Pongal
        history = [
            HumanMessage(content="Nutrition for indian chennai style pongal"),
            AIMessage(content="Here is the nutrition for Pongal..."),
            HumanMessage(content="Can u give me detailed recipe for it"),
            AIMessage(content="Here is the recipe for Chennai-Style Ven Pongal... Ingredients: Rice, Moong Dal, Ghee, Cashews...")
        ]
        
        # 2. User says "replace my lunch with this"
        query = "Can u replace my lunch with this, I had two servings of this"
        print(f"User Input: '{query}'")
        
        # Run chat stream
        # We want to see the PLAN generated by the planner
        
        print("\n--- Running Agent ---")
        for update in agent.run_chat_stream(query, user_id, history, {}, thread_id="context_test"):
            if "__STATUS__" in update:
                print(update)
            # We can't easily see the plan unless we add debug prints or inspect the state
            # But we can see the final response.
            if "Successfully updated" in str(update):
                print(f"\nFINAL RESPONSE:\n{update}")
                if "Pongal" in str(update):
                    print("PASS: Correctly identified Pongal.")
                elif "Beignet" in str(update):
                    print("FAIL: Hallucinated Beignet.")
                else:
                    print(f"FAIL: Identified something else: {update}")
                    
        return True

    except Exception as e:
        print(f"Reproduction Script Error: {e}")
        import traceback
        traceback.print_exc()
        return False

def main():
    session = get_snowpark_session()
    conn = get_snowflake_connection()
    if not session:
        print("Failed to get session")
        return
    reproduce_context_failure(session, conn)

if __name__ == "__main__":
    main()
