name: 'meal_mind'
version: '1.0.0'
config-version: 2

profile: 'meal_mind'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  meal_mind:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view  
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

vars:
  current_date: '{{ run_started_at.strftime("%Y-%m-%d") }}'